### ISSUE TITLE
Dataset Release?

### ISSUE THREAD

**Issue by cs329yangzhong** [jbshp/LongDocFACTScore#2]
Dear authors, would you release the annotated dataset?

**Comment by cs329yangzhong** [comment]
Dear authors, as the LREC-COLING conference has started, it would be greatly appreciated if you could share about your plans to release the dataset (as promised in the paper) to benefit the community. Thanks a lot!

**Comment by jbshp** [comment]
Hi, apologies for the delay. The data and evaluation scripts are released on the main branch now.
